.TH NIHL-CLI "1" "June 2016" "nihilo-cli 0.12"
.SH NAME
nihilo-cli \- a remote procedure call client for Nihilo Core.
.SH SYNOPSIS
nihilo-cli [options] <command> [params] \- Send command to Nihilo Core.
.TP
nihilo-cli [options] help \- Asks Nihilo Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the nihilo-cli program. nihilo-cli is an RPC client used to send commands to Nihilo Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBnihilod\fP, \fBnihilo.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
